### PR TITLE
[Finishes #162951503]set-up-landing-page

### PR DESCRIPTION
**Pull request by SimonOkello**
**What does this PR do?**
Creates a landing page for the user.

**Description of Task to be completed?**
Have the following requirements met:

1. Implement HTML for landing page
2. Add CSS for landing page
3. Add login and signup links on landing page

**How should this be manually tested?**

Clone  this repository  
`git clone https://github.com/SimonOkello/Questioner.git` 
`cd Questioner`
`cd UI`  
Open `index.html` in your favourite web browser

**Screenshots**

image

### CODE REVIEW

**Comment by Siffersari** [comment]
@SimonOkello  Great job. I love how you use the banner right there. Your could work on  branch naming. For naming branches follow the ft-user-landingpage-162951503 design.

**Comment by Mfalm3** [comment]
Apart from the minor branch name setback, I think you've done a fabulous job on the design

**Comment by Ogutu-Brian** [comment]
Great job

**Comment by wachiranduati** [comment]
nice design

**Pull request merged**
